[build]
  publish = ""
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Environment variables configuration
[context.production.environment]
  MONGODB_URL = ""
  MONGODB_DB = ""
  MONGODB_COLLECTION = "pbocdtl"

[context.branch-deploy.environment]
  MONGODB_URL = ""
  MONGODB_DB = ""
  MONGODB_COLLECTION = "pbocdtl"